Python kernel not connecting in rasdaman Jupyter Hub
When I try to run a Python Notebook in rasdaman Jupyter Hub, it fails to connect the Python 3 kernel. So the code cannot be executed. Can someone please have a look and fix it?

![Screenshot 2024-06-04 at 09 18 17](https://github.com/FAIRiCUBE/FAIRiCUBE-Hub-issue-tracker/assets/1943289/13a1e7ba-4a56-480c-8434-375b0db9d528)

We'll have a look at this on Monday, as my colleague is on vacation this week.
I've looked at this issue a couple of hours this evening with all I could do, but this is unknown issue to me when the kernel cannot be connected. I've asked on Jupyter notebook github / stackoverflow and I hope that they could give an answer soon   I've fixed the issue now, please have a look and close the ticket if it works for you now.
It is working now indeed, thanks!